name: Release

on:
  workflow_dispatch:

permissions:
  id-token: write

concurrency:
  group: Production
  cancel-in-progress: false

env:
  CI: true

jobs:
  stable-version:
    # https://docs.npmjs.com/generating-provenance-statements#publishing-packages-with-provenance-via-github-actions
    permissions:
      id-token: write
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/node
        with:
          working-directory: ${{ env.WORKING_DIRECTORY }}

      - run: npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
        shell: bash
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: Publish packages & Create Github Releases
        run: |
          git config --global user.email "bot@wundergraph.com"
          git config --global user.name "hardworker-bot"
          pnpm whoami
          pnpm release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
