name: Schema Loader CI
on:
  pull_request:
    paths:
      - 'packages/schema-loader/**/*'
      - '.github/workflows/schema-loader-ci.yaml'

concurrency:
  group: ${{github.workflow}}-${{github.head_ref}}
  cancel-in-progress: true

env:
  CI: true

jobs:
  build_test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/node

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run --filter ./packages/schema-loader build
